In [16]:
import numpy as np
import pandas as pd

 Numpy is used very widely and it will be used every where.
    for examole in deep learning, Computer vision, NLP evrywhere Numpy is used. it is an intigral part of data science. Even pandas written with help of numpy.

In [3]:
l = ['Vraj',1,2,3,4]

In [4]:
type(l)

list

The list and array is the same but they both are different datatypes. Array are represented in n- dimentiional arrays.

In [5]:
# to convert the list in to array
np.array(l)

array(['Vraj', '1', '2', '3', '4'], dtype='<U11')

In [6]:
type(np.array(l))

numpy.ndarray

If a single value has different datatype it automatically upcasts the whole list or array.

In [7]:
np.array([3,45,5,3.0,5])

array([ 3., 45.,  5.,  3.,  5.])

In [10]:
a = np.array([[1,2],[3,4]])

The list above inside array are converted into matrix. which means it converts the elements into rows and columns

In [11]:
a

array([[1, 2],
       [3, 4]])

In [13]:
a[1][1]

4

In [17]:
pd.DataFrame(a)

0  1
0  1  2
1  3  4

The ndmin parameter defines the number of dimension of an array. we can also get to know the dimension of array just by counting the number of square brackets. 

In [23]:
c=np.array([1,2,3,4,5],ndmin = 4)

In [24]:
c

array([[[[1, 2, 3, 4, 5]]]])

In [25]:
c[0]

array([[[1, 2, 3, 4, 5]]])

In [26]:
c[0][0]

array([[1, 2, 3, 4, 5]])

In [27]:
c[0][0][0]

array([1, 2, 3, 4, 5])

In [28]:
c[0][0][0][0]

1

In [29]:
np.asarray([1,2,3,45,6,7])

array([ 1,  2,  3, 45,  6,  7])

In [30]:
np.asanyarray([1,2,3,45,6,7])

array([ 1,  2,  3, 45,  6,  7])

The matrix is another form of an array but it returns the data with 2-D data

In [31]:
np.mat([1,2,3,4,5])

matrix([[1, 2, 3, 4, 5]])

In [32]:
a= [1,2,34,5,6]
np.asarray(a)

array([ 1,  2, 34,  5,  6])

In [33]:
np.asanyarray(a)

array([ 1,  2, 34,  5,  6])

In [34]:
np.asarray(a)

array([ 1,  2, 34,  5,  6])

In [35]:
np.mat(a)

matrix([[ 1,  2, 34,  5,  6]])

The np.asanyarray is doing that if the any of given data is in form array it will keep it as an array. if the given data is not in form of an array, it converts the data into an array.

In [37]:
np.asanyarray(np.mat(a)) #the matrix is an form of array so it kept as an array only

matrix([[ 1,  2, 34,  5,  6]])

We can make an matrix with the help of np.fromfunction

In [38]:
np.fromfunction(lambda i, j: i == j,(3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [45]:
np.mat(np.fromfunction(lambda i,j,k: i*j*k,(4,4,5),dtype='int'))

ValueError: shape too large to be a matrix.

In [60]:
a = np.fromfunction(lambda i,j,k: i*j*k,(4,3,2),dtype='int')

In [61]:
a

array([[[0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 1],
        [0, 2]],

       [[0, 0],
        [0, 2],
        [0, 4]],

       [[0, 0],
        [0, 3],
        [0, 6]]])

In [63]:
a.ndim # returns the dimention of an array

3

In [65]:
a.size #returns the number of elements in an array

24

In [66]:
a.shape #return the shape of an array

(4, 3, 2)

In [67]:
a.dtype

dtype('int32')

Data frames are 2-d array. we can not convert the above array into data frame

In [68]:
pd.DataFrame(a)

ValueError: Must pass 2-d input. shape=(4, 3, 2)

In [69]:
a = np.fromfunction(lambda i,j: i*j,(400,300),dtype='int')

In [70]:
pd.DataFrame(a)

0    1    2     3     4     5     6     7     8     9    ...     290  \
0      0    0    0     0     0     0     0     0     0     0  ...       0   
1      0    1    2     3     4     5     6     7     8     9  ...     290   
2      0    2    4     6     8    10    12    14    16    18  ...     580   
3      0    3    6     9    12    15    18    21    24    27  ...     870   
4      0    4    8    12    16    20    24    28    32    36  ...    1160   
..   ...  ...  ...   ...   ...   ...   ...   ...   ...   ...  ...     ...   
395    0  395  790  1185  1580  1975  2370  2765  3160  3555  ...  114550   
396    0  396  792  1188  1584  1980  2376  2772  3168  3564  ...  114840   
397    0  397  794  1191  1588  1985  2382  2779  3176  3573  ...  115130   
398    0  398  796  1194  1592  1990  2388  2786  3184  3582  ...  115420   
399    0  399  798  1197  1596  1995  2394  2793  3192  3591  ...  115710   

        291     292     293     294     295     296     297     298     299  
0         0       0       0       0       0       0       0       0       0  
1       291     292     293     294     295     296     297     298     299  
2       582     584     586     588     590     592     594     596     598  
3       873     876     879     882     885     888     891     894     897  
4      1164    1168    1172    1176    1180    1184    1188    1192    1196  
..      ...     ...     ...     ...     ...     ...     ...     ...     ...  
395  114945  115340  115735  116130  116525  116920  117315  117710  118105  
396  115236  115632  116028  116424  116820  117216  117612  118008  118404  
397  115527  115924  116321  116718  117115  117512  117909  118306  118703  
398  115818  116216  116614  117012  117410  117808  118206  118604  119002  
399  116109  116508  116907  117306  117705  118104  118503  118902  119301  

[400 rows x 300 columns]

We can creat random data using numpy

In [95]:
np.random.rand(100,4) # here, (100,4) is a size of an required array

array([[5.27104612e-02, 5.80046715e-01, 1.71698867e-01, 4.29843746e-01],
       [5.04124351e-02, 7.85185276e-01, 6.12200689e-01, 5.73905980e-02],
       [9.88134565e-01, 2.22183165e-01, 8.88650270e-01, 2.51108399e-01],
       [8.80835124e-01, 3.01211862e-01, 1.46446001e-01, 2.46203891e-01],
       [8.08720130e-01, 2.06763914e-01, 7.14492435e-01, 1.16251771e-01],
       [6.88151247e-01, 9.41642860e-01, 7.73461167e-01, 8.13570101e-02],
       [9.07787952e-01, 3.69703121e-01, 7.75338975e-01, 4.20692345e-01],
       [1.05124491e-01, 2.69021246e-01, 7.49646888e-01, 3.23632668e-01],
       [9.36721958e-01, 2.12616046e-01, 9.11623834e-01, 5.51401728e-01],
       [5.74598541e-01, 1.81794432e-01, 4.03596686e-01, 4.28569704e-01],
       [9.31047091e-01, 4.99422264e-01, 4.94707161e-02, 2.15886034e-01],
       [2.67842108e-01, 2.79699883e-02, 4.31856487e-01, 4.02737232e-01],
       [5.89345160e-02, 4.80454059e-01, 8.63871659e-01, 7.62073052e-01],
       [9.09857958e-01, 1.02726727e-01, 8.37797610e

In [77]:
np.random.randint(4,50) # it gives random integer between 4 to 50

46

In [79]:
np.random.randn(4,5) #this gives random numbers that are normally distributed(standard normal distribution)

array([[ 0.29796992, -0.33734585,  0.77140636,  0.05039566,  1.54267555],
       [ 1.55681418,  1.30445194,  1.69026397, -0.03891625, -0.70545799],
       [-0.45757056,  0.4744076 , -0.56813646,  2.17554487,  0.1906861 ],
       [-0.43507464,  0.62181212, -2.31750884,  1.85147002,  1.46235844]])

we can reshape the array but the reshape is only possible when the shape of an array must be equal to number of element.

In [80]:
a

array([[     0,      0,      0, ...,      0,      0,      0],
       [     0,      1,      2, ...,    297,    298,    299],
       [     0,      2,      4, ...,    594,    596,    598],
       ...,
       [     0,    397,    794, ..., 117909, 118306, 118703],
       [     0,    398,    796, ..., 118206, 118604, 119002],
       [     0,    399,    798, ..., 118503, 118902, 119301]])

In [81]:
a = np.fromfunction(lambda i,j,k: i*j*k,(4,3,2),dtype='int')

In [82]:
a

array([[[0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 1],
        [0, 2]],

       [[0, 0],
        [0, 2],
        [0, 4]],

       [[0, 0],
        [0, 3],
        [0, 6]]])

In [83]:
a.reshape(2,12)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 2],
       [0, 0, 0, 2, 0, 4, 0, 0, 0, 3, 0, 6]])

In [84]:
list(range(4,10))

[4, 5, 6, 7, 8, 9]

In [86]:
list(range(4,10,.2))

TypeError: 'float' object cannot be interpreted as an integer

In [88]:
# but in numpy we can jump decimally
np.arange(4,10,0.2)

array([4. , 4.2, 4.4, 4.6, 4.8, 5. , 5.2, 5.4, 5.6, 5.8, 6. , 6.2, 6.4,
       6.6, 6.8, 7. , 7.2, 7.4, 7.6, 7.8, 8. , 8.2, 8.4, 8.6, 8.8, 9. ,
       9.2, 9.4, 9.6, 9.8])

In [89]:
np.arange(4.5,10.3)

array([4.5, 5.5, 6.5, 7.5, 8.5, 9.5])

In [90]:
#slicing
a1 = np.arange(4,10,0.2)

In [91]:
a1[1:4]

array([4.2, 4.4, 4.6])

In [93]:
arr = np.random.rand(4,5)

In [94]:
arr

array([[0.77815348, 0.41152318, 0.24716081, 0.77024809, 0.04440072],
       [0.14189675, 0.67478399, 0.3710347 , 0.84920636, 0.83082645],
       [0.28157815, 0.84123882, 0.96387242, 0.15943739, 0.49050917],
       [0.65028777, 0.31470899, 0.72803774, 0.55991283, 0.9781499 ]])

In [97]:
arr[arr > 0.5]

array([0.77815348, 0.77024809, 0.67478399, 0.84920636, 0.83082645,
       0.84123882, 0.96387242, 0.65028777, 0.72803774, 0.55991283,
       0.9781499 ])

In [99]:
# if youn want to extract specified values
arr[[1,2],[2]]

array([0.3710347 , 0.96387242])

In [100]:
arr[1:3,2:3]

array([[0.3710347 ],
       [0.96387242]])

In [103]:
# we can overwrite the data also
arr[1:3]= 333

In [104]:
arr

array([[7.78153480e-01, 4.11523183e-01, 2.47160807e-01, 7.70248093e-01,
        4.44007177e-02],
       [3.33000000e+02, 3.33000000e+02, 3.33000000e+02, 3.33000000e+02,
        3.33000000e+02],
       [3.33000000e+02, 3.33000000e+02, 3.33000000e+02, 3.33000000e+02,
        3.33000000e+02],
       [6.50287768e-01, 3.14708988e-01, 7.28037737e-01, 5.59912826e-01,
        9.78149901e-01]])

In [108]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
a,b

(array([[1, 2],
        [3, 4]]),
 array([[5, 6],
        [7, 8]]))

In [109]:
a*b # this is elementwise multiplication

array([[ 5, 12],
       [21, 32]])

In [111]:
# matrix multiplication is also possible
m = a@b

Unlike python core it does not give zero division error in numpy it returns infinity instead.

In [113]:
m/0

C:\Users\49179\AppData\Local\Temp\ipykernel_10408\3791875896.py:1: RuntimeWarning: divide by zero encountered in divide
  m/0


array([[inf, inf],
       [inf, inf]])

In [116]:
np.zeros(5) # np.zeros() return an array of all zero values of given size

array([0., 0., 0., 0., 0.])

In [117]:
# if we want 2-d array we can get
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [118]:
np.zeros((3,4,5))

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [119]:
# like np.zeros, there is function like np.ones()
np.ones(5)

array([1., 1., 1., 1., 1.])

In [120]:
np.ones((3,4,5))

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [121]:
# We can perform some operations with np.zeros
np.zeros(5)+5

array([5., 5., 5., 5., 5.])

In [123]:
5+np.ones((3,4))

array([[6., 6., 6., 6.],
       [6., 6., 6., 6.],
       [6., 6., 6., 6.]])

In [129]:
np.empty((4,4))

array([[0.00000000e+000, 0.00000000e+000, 2.12199579e-314,
        2.12199579e-314],
       [4.24399158e-314, 4.24399158e-314, 6.36598737e-314,
        6.36598737e-314],
       [2.12199579e-314, 6.36598737e-314, 2.12199579e-314,
        6.36598737e-314],
       [2.12199579e-314, 6.36598737e-314, 2.12199579e-314,
        6.36598737e-314]])

# Numpy functions

In [132]:
# np.linspace generates 50 numbers by degault that are evenly distanced between start to end
np.linspace(1,5)

array([1.        , 1.08163265, 1.16326531, 1.24489796, 1.32653061,
       1.40816327, 1.48979592, 1.57142857, 1.65306122, 1.73469388,
       1.81632653, 1.89795918, 1.97959184, 2.06122449, 2.14285714,
       2.2244898 , 2.30612245, 2.3877551 , 2.46938776, 2.55102041,
       2.63265306, 2.71428571, 2.79591837, 2.87755102, 2.95918367,
       3.04081633, 3.12244898, 3.20408163, 3.28571429, 3.36734694,
       3.44897959, 3.53061224, 3.6122449 , 3.69387755, 3.7755102 ,
       3.85714286, 3.93877551, 4.02040816, 4.10204082, 4.18367347,
       4.26530612, 4.34693878, 4.42857143, 4.51020408, 4.59183673,
       4.67346939, 4.75510204, 4.83673469, 4.91836735, 5.        ])

In [131]:
np.arange(1,5) # np.arrange is different like this

array([1, 2, 3, 4])

In [133]:
# we can have the amount of numbers we want
np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [135]:
np.linspace(1,5,10,endpoint= False) # we won't get the last point

array([1. , 1.4, 1.8, 2.2, 2.6, 3. , 3.4, 3.8, 4.2, 4.6])

In [137]:
np.linspace(1,5,10,retstep=True) # we can get the step sizes also

(array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
        3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ]),
 0.4444444444444444)

In [139]:
np.logspace(1,3,10,base=10) # this one is the similar to the linspace and returns the value with its log values

array([  10.        ,   16.68100537,   27.82559402,   46.41588834,
         77.42636827,  129.1549665 ,  215.443469  ,  359.38136638,
        599.48425032, 1000.        ])

In [172]:
# Another function is max() to find the maximum
a = np.arange(1,26).reshape(5,5)

In [173]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [174]:
a.max()

25

In [175]:
a.max(axis=0)

array([21, 22, 23, 24, 25])

In [176]:
a.max(axis=1)

array([ 5, 10, 15, 20, 25])

In [177]:
a/0

C:\Users\49179\AppData\Local\Temp\ipykernel_10408\4102073204.py:1: RuntimeWarning: divide by zero encountered in divide
  a/0


array([[inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf]])

In [178]:
a*25

array([[ 25,  50,  75, 100, 125],
       [150, 175, 200, 225, 250],
       [275, 300, 325, 350, 375],
       [400, 425, 450, 475, 500],
       [525, 550, 575, 600, 625]])

In [179]:
pow(a,3) # it equals to a**3

array([[    1,     8,    27,    64,   125],
       [  216,   343,   512,   729,  1000],
       [ 1331,  1728,  2197,  2744,  3375],
       [ 4096,  4913,  5832,  6859,  8000],
       [ 9261, 10648, 12167, 13824, 15625]], dtype=int32)

In [185]:
b= np.array([2,3,5,4,7])

In [186]:
a+b # this is a row-wise addition

array([[ 3,  5,  8,  8, 12],
       [ 8, 10, 13, 13, 17],
       [13, 15, 18, 18, 22],
       [18, 20, 23, 23, 27],
       [23, 25, 28, 28, 32]])

In [187]:
# to perform column wise addition we need to take transpose
a + b.T

array([[ 3,  5,  8,  8, 12],
       [ 8, 10, 13, 13, 17],
       [13, 15, 18, 18, 22],
       [18, 20, 23, 23, 27],
       [23, 25, 28, 28, 32]])

In [188]:
# The answer after does not change because b is a 1-D array we need to reshape into 2-D array

b= b.reshape(1,-1)

In [189]:
b.T

array([[2],
       [3],
       [5],
       [4],
       [7]])

In [190]:
a + b.T

array([[ 3,  4,  5,  6,  7],
       [ 9, 10, 11, 12, 13],
       [16, 17, 18, 19, 20],
       [20, 21, 22, 23, 24],
       [28, 29, 30, 31, 32]])

In [191]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [192]:
np.sqrt(a) # To find the square root 

array([[1.        , 1.41421356, 1.73205081, 2.        , 2.23606798],
       [2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766],
       [3.31662479, 3.46410162, 3.60555128, 3.74165739, 3.87298335],
       [4.        , 4.12310563, 4.24264069, 4.35889894, 4.47213595],
       [4.58257569, 4.69041576, 4.79583152, 4.89897949, 5.        ]])

In [194]:
np.exp(a) # to find the exponetial

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
        1.48413159e+02],
       [4.03428793e+02, 1.09663316e+03, 2.98095799e+03, 8.10308393e+03,
        2.20264658e+04],
       [5.98741417e+04, 1.62754791e+05, 4.42413392e+05, 1.20260428e+06,
        3.26901737e+06],
       [8.88611052e+06, 2.41549528e+07, 6.56599691e+07, 1.78482301e+08,
        4.85165195e+08],
       [1.31881573e+09, 3.58491285e+09, 9.74480345e+09, 2.64891221e+10,
        7.20048993e+10]])

In [207]:
x= np.asarray([12,34,56,78])

In [208]:
y=x

In [209]:
y

array([12, 34, 56, 78])

In [210]:
z= np.copy(x)

In [211]:
z

array([12, 34, 56, 78])

In [212]:
x[2] = 45

In [213]:
x

array([12, 34, 45, 78])

In [214]:
y

array([12, 34, 45, 78])

In [215]:
z

array([12, 34, 56, 78])